version: "3"

tasks:
  build:
    cmds:
      - CGO_ENABLED=0 go build -o gh-stars-backup ./main.go
  build-docker:
    cmds:
      - docker build -t gh-stars-backup .
  init-multi-arch:
    cmds:
      - docker buildx create --name multi-arch --use
  build-multi-arch:
    cmds: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t gh-stars-backup .
